import type { ElementRecord } from '@/src/core/block/element/types';
import { BASE_GLOBAL_ATTRIBUTES, GENERAL_ARIA_ATTRIBUTES, TEXT_ONLY_ATTRIBUTES, PHRASING_CONTENT, PHRASING_WITH_RUBY, VOID_CONTENT } from './shared';

const PHRASING_ATTRIBUTES = [...BASE_GLOBAL_ATTRIBUTES, ...GENERAL_ARIA_ATTRIBUTES, ...TEXT_ONLY_ATTRIBUTES];

export const PHRASING_ELEMENTS: Partial<ElementRecord> = {
	span: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Generic inline container with no semantic meaning. Useful for styling parts of text.',
	},
	b: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Stylistically offset text (typically bold) without conveying importance.',
	},
	strong: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Indicates strong importance, seriousness, or urgency.',
	},
	i: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Text in an alternate voice or mood (typically italic), such as technical terms or idioms.',
	},
	em: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Emphasized text indicating stress emphasis.',
	},
	u: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Text that is stylistically different from normal text (often underlined).',
	},
	small: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Side-comments and small print; typically rendered in a smaller font.',
	},
	mark: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Text highlighted for reference or relevance within a context.',
	},
	sub: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Subscript inline text for chemical formulas, math, etc.',
	},
	sup: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Superscript inline text for footnotes, exponents, etc.',
	},
	code: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Inline fragment of computer code.',
	},
	abbr: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Abbreviation or acronym; title attribute can provide expansion.',
	},
	s: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Text that is no longer accurate or relevant (rendered with a strikethrough).',
	},
	del: {
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'cite', 'datetime'],
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'A range of text that has been removed from a document. May carry cite/datetime meta.',
	},
	ins: {
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'cite', 'datetime'],
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'A range of text that has been added to a document. May carry cite/datetime meta.',
	},
	q: {
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'cite'],
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Short inline quotation; cite attribute may reference the source.',
	},
	cite: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Title of a work or reference to a source.',
	},
	dfn: {
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'title'],
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Term being defined; title attribute can provide a definition hint.',
	},
	var: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Variable in programming or mathematics.',
	},
	samp: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Sample output from programs or systems.',
	},
	kbd: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'User input, typically keyboard input.',
	},
	time: {
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'datetime'],
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Date and/or time, optionally machine-readable via datetime attribute.',
	},
	data: {
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'value'],
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Associates content with a machine-readable value.',
	},
	wbr: {
		allowedAttributes: [...BASE_GLOBAL_ATTRIBUTES, ...GENERAL_ARIA_ATTRIBUTES],
		allowedElements: VOID_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Word break opportunity (void element) suggesting where line breaks may occur.',
	},
	bdi: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Isolates a span of text with a different directionality from its surroundings.',
	},
	bdo: {
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'dir'],
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Overrides the text direction of its children using the dir attribute.',
	},
	ruby: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_WITH_RUBY,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Ruby annotation for East Asian typography. Contains base text with rt/rp annotations.',
	},
	rt: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Ruby text providing pronunciation or annotation.',
	},
	rp: {
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedElements: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueElements: null,
		orderedElements: null,
		description: 'Fallback parentheses for browsers that do not support ruby annotations.',
	},
};
