// Types
import type { ElementDefinition } from '@/core/block/element/types';

// Shared
import { BASE_GLOBAL_ATTRIBUTES, GENERAL_ARIA_ATTRIBUTES, TEXT_ONLY_ATTRIBUTES, PHRASING_CONTENT, PHRASING_WITH_RUBY, VOID_CONTENT } from './shared';

const PHRASING_ATTRIBUTES = [...BASE_GLOBAL_ATTRIBUTES, ...GENERAL_ARIA_ATTRIBUTES, ...TEXT_ONLY_ATTRIBUTES];

export const PHRASING_DEFINITIONS: ElementDefinition[] = [
	{
		key: 'span',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Generic inline container with no semantic meaning. Useful for styling parts of text.',
	},
	{
		key: 'b',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Stylistically offset text (typically bold) without conveying importance.',
	},
	{
		key: 'strong',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Indicates strong importance, seriousness, or urgency.',
	},
	{
		key: 'i',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Text in an alternate voice or mood (typically italic), such as technical terms or idioms.',
	},
	{
		key: 'em',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Emphasized text indicating stress emphasis.',
	},
	{
		key: 'u',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Text that is stylistically different from normal text (often underlined).',
	},
	{
		key: 'small',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Side-comments and small print; typically rendered in a smaller font.',
	},
	{
		key: 'mark',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Text highlighted for reference or relevance within a context.',
	},
	{
		key: 'sub',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Subscript inline text for chemical formulas, math, etc.',
	},
	{
		key: 'sup',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Superscript inline text for footnotes, exponents, etc.',
	},
	{
		key: 'code',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Inline fragment of computer code.',
	},
	{
		key: 'abbr',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Abbreviation or acronym; title attribute can provide expansion.',
	},
	{
		key: 's',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Text that is no longer accurate or relevant (rendered with a strikethrough).',
	},
	{
		key: 'del',
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'cite', 'datetime'],
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'A range of text that has been removed from a document. May carry cite/datetime meta.',
	},
	{
		key: 'ins',
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'cite', 'datetime'],
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'A range of text that has been added to a document. May carry cite/datetime meta.',
	},
	{
		key: 'q',
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'cite'],
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Short inline quotation; cite attribute may reference the source.',
	},
	{
		key: 'cite',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Title of a work or reference to a source.',
	},
	{
		key: 'dfn',
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'title'],
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Term being defined; title attribute can provide a definition hint.',
	},
	{
		key: 'var',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Variable in programming or mathematics.',
	},
	{
		key: 'samp',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Sample output from programs or systems.',
	},
	{
		key: 'kbd',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'User input, typically keyboard input.',
	},
	{
		key: 'time',
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'datetime'],
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Date and/or time, optionally machine-readable via datetime attribute.',
	},
	{
		key: 'data',
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'value'],
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Associates content with a machine-readable value.',
	},
	{
		key: 'wbr',
		allowedAttributes: [...BASE_GLOBAL_ATTRIBUTES, ...GENERAL_ARIA_ATTRIBUTES],
		allowedChildren: VOID_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Word break opportunity (void element) suggesting where line breaks may occur.',
	},
	{
		key: 'bdi',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Isolates a span of text with a different directionality from its surroundings.',
	},
	{
		key: 'bdo',
		allowedAttributes: [...PHRASING_ATTRIBUTES, 'dir'],
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Overrides the text direction of its children using the dir attribute.',
	},
	{
		key: 'ruby',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_WITH_RUBY,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Ruby annotation for East Asian typography. Contains base text with rt/rp annotations.',
	},
	{
		key: 'rt',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Ruby text providing pronunciation or annotation.',
	},
	{
		key: 'rp',
		allowedAttributes: PHRASING_ATTRIBUTES,
		allowedChildren: PHRASING_CONTENT,
		forbiddenAncestors: null,
		uniqueChildren: null,
		orderedChildren: null,
		description: 'Fallback parentheses for browsers that do not support ruby annotations.',
	},
];
