import { BlockTagKeys } from "@/types/block/tag";

export const FlowContent: BlockTagKeys[] = [
	'a',
	'abbr',
	'address',
	'article',
	'aside',
	'audio',
	'b',
	'blockquote',
	'br',
	'button',
	'code',
	'data',
	'del',
	'div',
	'dl',
	'em',
	'footer',
	'h1',
	'h2',
	'h3',
	'h4',
	'h5',
	'h6',
	'header',
	'hgroup',
	'hr',
	'i',
	'image',
	'input',
	'ins',
	'kbd',
	'label',
	'main',
	'mark',
	'menu',
	'meter',
	'nav',
	'section',
	'ol',
	'output',
	'p',
	'picture',
	'pre',
	'q',
	'samp',
	'small',
	'span',
	'strong',
	'sub',
	'sup',
	'table',
	'textarea',
	'time',
	'u',
	'var',
	'wbr',
	'video',
	// List content
	'ul',
	'li',
	'dt',
	'dd',
	// Table content
	'caption',
	'colgroup',
	'col',
	'thead',
	'tbody',
	'tfoot',
	'tr',
	'td',
	'th',
	// Form content
	'form',
	'select',
	'fieldset',
	'legend',
	'optgroup',
	'option',
	'progress',
	// Embedded content
	'img',
];

export const PalpableContent: BlockTagKeys[] = [
	// Headings
	'h1',
	'h2',
	'h3',
	'h4',
	'h5',
	'h6',
	// Text/inline
	'a',
	'span',
	'strong',
	'em',
	'b',
	'i',
	'u',
	'abbr',
	'mark',
	'small',
	'sub',
	'sup',
	's',
	'del',
	'ins',
	'code',
	'time',
	'var',
	'kbd',
	'samp',
	'data',
	'cite',
	'q',
	'button',
	'label',
	'input',
	'select',
	'textarea',
	// Block/structural
	'p',
	'div',
	'section',
	'article',
	'nav',
	'aside',
	'header',
	'footer',
	'main',
	'address',
	'pre',
	'blockquote',
	// Lists
	'ul',
	'ol',
	'li',
	'dl',
	'dt',
	'dd',
	'menu',
	// Tables
	'table',
	'caption',
	'colgroup',
	'col',
	'thead',
	'tbody',
	'tfoot',
	'tr',
	'td',
	'th',
	// Media/embedded
	'img',
	'audio',
	'video',
	'picture',
	// Misc
	'hr',
	'br',
	'wbr',
	'output',
	'progress',
	'meter',
] as const;

export const SectioningContent: BlockTagKeys[] = ['section', 'article', 'nav', 'aside'] as const;

export const HeadingContent: BlockTagKeys[] = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] as const;

export const PhrasingContent: BlockTagKeys[] = ['span', 'a', 'strong', 'em', 'b', 'i', 'u', 'abbr', 'br', 'mark', 'small', 'sub', 'sup', 's', 'del', 'ins', 'code', 'time', 'var', 'kbd', 'samp', 'data', 'cite', 'q', 'wbr', 'button', 'input', 'label', 'select', 'textarea', 'img'] as const;

export const EmbeddedContent: BlockTagKeys[] = ['img', 'audio', 'video', 'picture'] as const;

export const InteractiveContent: BlockTagKeys[] = ['a', 'button', 'input', 'select', 'textarea', 'label'] as const;

export const FormContent: BlockTagKeys[] = ['form', 'input', 'button', 'select', 'textarea', 'label', 'fieldset', 'legend', 'optgroup', 'option', 'output', 'progress', 'meter'] as const;

export const AllContent: BlockTagKeys[] = [
	//
	...FlowContent,
	...PalpableContent,
	...SectioningContent,
	...HeadingContent,
	...PhrasingContent,
	...EmbeddedContent,
	...InteractiveContent,
	...FormContent,
] as const;
