import { CSSPropertyDefs } from './property';

// New: Centralized descriptions for all CSS properties
export const CSSPropertyDesc: Record<keyof typeof CSSPropertyDefs, string> = {
	// ============ Display & Layout =============
	display: 'Controls the element’s display type and how it participates in layout.',

	'flex-direction': 'Defines the main axis direction for flex container children.',
	'flex-wrap': 'Specifies whether flex items are forced onto a single line or can wrap.',
	'flex-flow': 'Shorthand for setting both flex-direction and flex-wrap.',
	'flex-grow': 'Determines how much a flex item will grow relative to others in the container.',
	'flex-shrink': 'Determines how much a flex item will shrink relative to others in the container.',
	'flex-basis': 'Specifies the initial main size of a flex item before space distribution.',
	'justify-content': 'Aligns flex items along the main axis of the flex container.',
	'align-items': 'Aligns flex items along the cross axis of the flex container.',
	'align-content': 'Aligns flex lines within a flex container when there is extra space.',
	'justify-items': 'Aligns items along the main axis in a single line or grid cell.',

	'grid-auto-flow': 'Controls the placement algorithm for auto-placed grid items.',
	'grid-template-columns': 'Defines the column structure of the grid.',
	'grid-template-rows': 'Defines the row structure of the grid.',
	'grid-auto-columns': 'Specifies the size of columns created automatically in the grid.',
	'grid-auto-rows': 'Specifies the size of rows created automatically in the grid.',
	'row-gap': 'Sets the size of the gap between grid rows.',
	'column-gap': 'Sets the size of the gap between grid columns.',
	gap: 'Shorthand for setting both row-gap and column-gap.',

	direction: 'Specifies the base writing direction for text and layout.',
	'box-sizing': 'Controls how the total width and height of an element are calculated.',
	'object-fit': 'Specifies how replaced content should be resized to fit its container.',
	float: 'Removes the element from normal flow and positions it to the left or right.',
	clear: 'Specifies which sides of an element floating elements are not allowed to be adjacent to.',
	visibility: 'Specifies whether the element is visible, hidden, or collapses its space.',

	// ============ Size & Scroll =============
	width: 'Specifies the width of the element’s content area.',
	'min-width': 'Sets the minimum width the element’s content area can be.',
	'max-width': 'Sets the maximum width the element’s content area can be.',
	height: 'Specifies the height of the element’s content area.',
	'min-height': 'Sets the minimum height the element’s content area can be.',
	'max-height': 'Sets the maximum height the element’s content area can be.',
	'aspect-ratio': 'Sets a preferred width-to-height ratio for the element’s box.',
	overflow: 'Controls what happens when content overflows the element’s box.',

	'scroll-behavior': 'Specifies the scrolling behavior for the element when scrolling is triggered.',
	'overscroll-behavior': 'Specifies the behavior when scrolling reaches the boundary of a scroll container.',
	'scroll-snap-type': 'Defines how the element’s children snap to a grid or points when scrolling.',
	'scroll-snap-align': 'Defines the alignment of the element’s children within the scroll container.',
	'scroll-snap-stop': 'Controls whether the scroll snap point is always respected or not.',
	'scroll-margin': 'Sets the margin around the element for scroll snapping.',
	'scroll-margin-block': 'Sets the margin around the element for scroll snapping in the block direction.',
	'scroll-margin-inline': 'Sets the margin around the element for scroll snapping in the inline direction.',
	'scroll-padding': 'Sets the padding around the element for scroll snapping.',
	'scroll-padding-block': 'Sets the padding around the element for scroll snapping in the block direction.',
	'scroll-padding-inline': 'Sets the padding around the element for scroll snapping in the inline direction.',

	// ============ Position & Spacing =============
	position: 'Specifies the positioning method for the element.',
	top: 'Specifies the vertical offset of a positioned element from its containing block’s top edge.',
	right: 'Specifies the horizontal offset of a positioned element from its containing block’s right edge.',
	bottom: 'Specifies the vertical offset of a positioned element from its containing block’s bottom edge.',
	left: 'Specifies the horizontal offset of a positioned element from its containing block’s left edge.',
	'z-index': 'Controls the stacking order of positioned elements.',

	'padding-top': 'Sets the space between the element’s content and its top border.',
	'padding-right': 'Sets the space between the element’s content and its right border.',
	'padding-bottom': 'Sets the space between the element’s content and its bottom border.',
	'padding-left': 'Sets the space between the element’s content and its left border.',
	padding: 'Sets the space between the element’s content and all its borders.',

	'margin-top': 'Sets the space outside the element’s top border.',
	'margin-right': 'Sets the space outside the element’s right border.',
	'margin-bottom': 'Sets the space outside the element’s bottom border.',
	'margin-left': 'Sets the space outside the element’s left border.',
	margin: 'Sets the space outside all the element’s borders.',


	// ============ Background & Mask =============
	'background-color': 'Sets the background color of the element.',
	'background-position': 'Positions the background image within the element.',
	'background-size': 'Resizes the background image of the element.',
	'background-repeat': 'Repeats the background image of the element.',
	'background-image': 'Applies a background image to the element.',

	'background-attachment': 'Determines if the background image scrolls with the page or stays fixed.',
	'background-clip': 'Defines how far the background extends within the element.',
	'background-origin': 'Determines the positioning area for the background image.',
	'background-blend-mode': 'Specifies how multiple background layers blend with each other.',

	'mask-image': 'Applies a mask image to the element.',
	'mask-position': 'Positions the mask image within the element.',
	'mask-size': 'Resizes the mask image of the element.',
	'mask-repeat': 'Repeats the mask image of the element.',
	'mask-clip': 'Defines how far the mask extends within the element.',
	'mask-origin': 'Determines the positioning area for the mask image.',
	'mask-mode': 'Specifies the mask mode for the element.',
	'mask-type': 'Specifies the mask type for the element.',
	'mask-composite': 'Defines how multiple mask images are combined.',
	// ============ Border =============
	'border-width': "Sets the width of all sides of the element's borders.",
	'border-style': "Sets the style of all sides of the element's borders.",
	'border-color': "Sets the color of all sides of the element's borders.",
	'border-radius': 'Rounds all corners of the element.',

	'border-top-width': 'Sets the width of the top border of the element.',
	'border-top-style': 'Sets the style of the top border of the element.',
	'border-top-color': 'Sets the color of the top border of the element.',
	'border-right-width': 'Sets the width of the right border of the element.',
	'border-right-style': 'Sets the style of the right border of the element.',
	'border-right-color': 'Sets the color of the right border of the element.',
	'border-bottom-width': 'Sets the width of the bottom border of the element.',
	'border-bottom-style': 'Sets the style of the bottom border of the element.',
	'border-bottom-color': 'Sets the color of the bottom border of the element.',
	'border-left-width': 'Sets the width of the left border of the element.',
	'border-left-style': 'Sets the style of the left border of the element.',
	'border-left-color': 'Sets the color of the left border of the element.',

	'border-top-left-radius': 'Rounds the top-left corner of the element.',
	'border-top-right-radius': 'Rounds the top-right corner of the element.',
	'border-bottom-left-radius': 'Rounds the bottom-left corner of the element.',
	'border-bottom-right-radius': 'Rounds the bottom-right corner of the element.',

	'border-image-source': 'Specifies the source image for the border.',
	'border-image-slice': 'Defines how the border image is sliced into regions.',
	'border-image-width': 'Sets the width of the border image.',
	'border-image-outset': 'Specifies the amount by which the border image area extends beyond the border box.',
	'border-image-repeat': 'Specifies how the border image is repeated or stretched.',

	'outline-width': 'Sets the width of the outline around the element.',
	'outline-style': 'Sets the style of the outline around the element.',
	'outline-color': 'Sets the color of the outline around the element.',
	'outline-offset': 'Sets the space between the outline and the edge of the element’s border.',

	// ============ Font & Text =============
	'font-family': 'Specifies the font family for the element’s text.',
	'font-size': 'Sets the size of the font.',
	'font-weight': 'Sets the thickness or boldness of the font.',
	'font-style': 'Specifies the font style.',
	'line-height': 'Sets the height of each line of text.',

	color: 'Sets the color of the text.',
	'text-align': 'Sets the horizontal alignment of text within its container.',
	'text-decoration': 'Specifies decoration added to text, such as underline, overline, or line-through.',
	'text-transform': 'Controls the capitalization of text.',
	'text-indent': 'Indents the first line of text by a specified amount.',
	'text-shadow': 'Adds shadow effects to text.',
	'text-overflow': 'Specifies how overflowed content that is not displayed is signaled to the user.',
	'text-orientation': 'Specifies the orientation of text characters in a line.',
	'text-align-last': 'Specifies how the last line of a block or a line right before a forced line break is aligned.',
	'text-combine-upright': 'Combines multiple characters into a single upright character, useful for vertical text layout.',

	'white-space': 'Controls how whitespace inside the element is handled.',
	'word-break': 'Specifies how words should break when reaching the end of a line.',
	'writing-mode': 'Defines whether lines of text are laid out horizontally or vertically.',
	'letter-spacing': 'Sets the spacing between characters of text.',
	'line-break': 'Sets how/where to break lines within text.',
	'word-spacing': 'Sets the spacing between words in text.',

	'column-count': 'Specifies the number of columns an element should be divided into for multi-column layout.',
	'column-width': 'Specifies the ideal width of columns in a multi-column layout.',
	'column-rule-width': 'Specifies the width of the line that separates columns in a multi-column layout.',
	'column-rule-style': 'Specifies the style of the line that separates columns.',
	'column-rule-color': 'Specifies the color of the line that separates columns.',
	'break-before': 'Specifies whether a page, column, or region break should occur before the element.',
	'break-inside': 'Specifies whether a page, column, or region break should occur inside the element.',
	'break-after': 'Specifies whether a page, column, or region break should occur after the element.',
	'column-span': 'Specifies how many columns an element should span across in a multi-column layout.',
	'column-fill': 'Specifies how content should be distributed between columns.',

	// -------------------------------- EFFECTS --------------------------------
	filter: 'Applies graphical effects such as blurring, brightness, contrast, and more to the element itself.',
	'backdrop-filter': 'Applies graphical effects such as blurring or color shifting to the area behind an element.',
	'box-shadow': 'Adds shadow effects around the element’s frame.',
	transform: 'Transforms the element in 2D or 3D space.',
	opacity: 'Sets the transparency level of the element, affecting its content and children.',
};
