import { CSSPropertyDefs } from "./property";

// New: Centralized descriptions for all CSS properties
export const CSSPropertyDesc: Partial<Record<keyof typeof CSSPropertyDefs, string>> = {
    display: 'Defines the display behavior of an element',
    visibility: 'Specifies whether an element is visible',
    opacity: 'Sets the opacity level for an element',
    'box-sizing': 'Defines how the width and height of an element are calculated',
    'aspect-ratio': 'Sets a preferred aspect ratio for the box',
    float: 'Specifies whether an element should float to the left, right, or not at all',
    clear: 'Specifies on which sides of an element floating elements are not allowed',
    'flex-direction': 'Specifies the direction of flex items',
    'flex-wrap': 'Specifies whether flex items are forced on one line or can wrap',
    'flex-flow': 'Shorthand for flex-direction and flex-wrap',
    'flex-grow': 'Specifies how much a flex item will grow relative to others',
    'flex-shrink': 'Specifies how much a flex item will shrink relative to others',
    'flex-basis': 'Specifies the initial size of a flex item',
    'justify-content': 'Aligns flex items along the main axis',
    'align-items': 'Aligns flex items along the cross axis',
    'align-content': "Aligns flex lines when there's extra space on cross axis",
    'justify-items': 'Aligns flex items along the main axis in a single line',
    'grid-auto-flow': 'Controls how auto-placed items are inserted in the grid',
    'grid-template-columns': 'Defines the columns of the grid',
    'grid-template-rows': 'Defines the rows of the grid',
    'grid-auto-columns': 'Specifies the size of implicitly-created grid columns',
    'grid-auto-rows': 'Specifies the size of implicitly-created grid rows',
    'row-gap': 'Sets the size of the gap between grid rows',
    'column-gap': 'Sets the size of the gap between grid columns',
    gap: 'Shorthand for row-gap and column-gap',
    width: 'The width of the element.',
    'min-width': 'The minimum width of the element.',
    'max-width': 'The maximum width of the element.',
    height: 'The height of the element.',
    'min-height': 'The minimum height of the element.',
    'max-height': 'The maximum height of the element.',
    overflow: 'Specifies what happens if content overflows an element',
    'overflow-x': 'Specifies overflow behavior on x-axis',
    'overflow-y': 'Specifies overflow behavior on y-axis',
    position: 'Specifies the type of positioning for an element',
    top: 'Specifies the top position of positioned element',
    right: 'Specifies the right position of positioned element',
    bottom: 'Specifies the bottom position of positioned element',
    left: 'Specifies the left position of positioned element',
    'z-index': 'Specifies the stack order of an element',
    'padding-top': 'Sets the top padding of an element',
    'padding-right': 'Sets the right padding of an element',
    'padding-bottom': 'Sets the bottom padding of an element',
    'padding-left': 'Sets the left padding of an element',
    padding: 'Shorthand for all padding properties',
    'margin-top': 'Sets the top margin of an element',
    'margin-right': 'Sets the right margin of an element',
    'margin-bottom': 'Sets the bottom margin of an element',
    'margin-left': 'Sets the left margin of an element',
    margin: 'Shorthand for all margin properties',
    'background-color': 'Sets the background color of an element',
    'background-image': 'Sets one or more background images',
    'background-position': 'Sets the starting position of a background image',
    'background-size': 'Specifies the size of background images',
    'background-repeat': 'Sets how background images are repeated',
    'background-attachment': 'Sets whether background images scroll with content',
    'background-clip': 'Defines how far the background extends',
    'background-origin': 'Sets the positioning area of background images',
    'border-top-width': 'Sets the width of the top border',
    'border-right-width': 'Sets the width of the right border',
    'border-bottom-width': 'Sets the width of the bottom border',
    'border-left-width': 'Sets the width of the left border',
    'border-width': 'Shorthand for all border width properties',
    'border-top-style': 'Sets the style of the top border',
    'border-right-style': 'Sets the style of the right border',
    'border-bottom-style': 'Sets the style of the bottom border',
    'border-left-style': 'Sets the style of the left border',
    'border-style': 'Shorthand for all border style properties',
    'border-top-color': 'Sets the color of the top border',
    'border-right-color': 'Sets the color of the right border',
    'border-bottom-color': 'Sets the color of the bottom border',
    'border-left-color': 'Sets the color of the left border',
    'border-color': 'Shorthand for all border color properties',
    'border-radius': 'Rounds the corners of an element',
    'border-top-left-radius': 'Rounds the top-left corner of an element',
    'border-top-right-radius': 'Rounds the top-right corner of an element',
    'border-bottom-right-radius': 'Rounds the bottom-right corner of an element',
    'border-bottom-left-radius': 'Rounds the bottom-left corner of an element',
    'outline-width': 'Sets the width of the outline',
    'outline-style': 'Sets the style of the outline',
    'outline-color': 'Sets the color of the outline',
    'outline-offset': 'Sets the space between outline and border',
    outline: 'Shorthand for outline properties',
    'font-family': 'Specifies the font for an element',
    'font-size': 'Sets the size of the font',
    'font-weight': 'Sets the weight (boldness) of the font',
    'font-style': 'Specifies the font style',
    'line-height': 'Sets the height of a line box',
    color: 'Sets the color of the text',
    'text-align': 'Sets the horizontal alignment of text',
    'text-decoration-line': 'Sets the kind of text decoration',
    'text-decoration-color': 'Sets the color of text decoration',
    'text-decoration-style': 'Sets the style of text decoration',
    'text-decoration-thickness': 'Sets the thickness of text decoration',
    'text-transform': 'Controls text capitalization',
    'text-indent': 'Indents the first line of text',
    'text-shadow': 'Adds shadow to text',
    'text-overflow': 'Specifies how overflowed content is signaled',
    'white-space': 'Controls how whitespace is handled',
    'word-break': 'Specifies line breaking rules',
    'writing-mode': 'Defines text layout direction',
    'box-shadow': 'Adds shadow effects around an element',
    transform: 'Applies 2D or 3D transformations',
    filter: 'Applies graphical effects like blur',
    'backdrop-filter': 'Applies filters to area behind element',
    'object-fit': 'Specifies how content should fit its container',
    'object-position': 'Specifies the alignment of content',
    cursor: 'Specifies the mouse cursor',
    'scroll-behavior': 'Specifies scrolling behavior',
};